app:
  portal:
    reg:
      selfDescriptionUrl: ${PORTAL_REGI_SD_URL:https://localhost:8089/api/administration/registration/clearinghouse/selfDescription}
    client:
      id: ${KEYCLOAK_CLIENT_ID:sa-cl2-01}
      secret: ${KEYCLOAK_CLIENT_SECRET:xxxxx}
      tokenUrl: ${AUTH_SERVER_TOKEN_URL:https://localhost:8000/auth/realms/CX-Central/protocol/openid-connect/token}