replicaCount: 1

image:
  repository: clearing-house
  pullPolicy: IfNotPresent
  tag: "latest"


serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: clearing-house.cx.the-sense.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: clearing-house-tls
      hosts:
        - clearing-house.cx.the-sense.io

envs:
  APPLICATION_PORT: 8080
  AUTH_SERVER_TOKEN_URL: "https://centralidp.cx.the-sense.io/auth/realms/CX-Central/protocol/openid-connect/token"
  PORTAL_REGI_SD_URL: "https://portal-backend.cx.the-sense.io/api/administration/registration/clearinghouse/selfDescription"
  RETRY_COUNT: 5
  PORTAL_CONNECTOR_SD_URL: "https://portal-backend.cx.the-sense.io/api/administration/Connectors/clearinghouse/selfDescription"


secrets:
  KEYCLOAK_CLIENT_ID: "<path:clearing-house/data/idp#client-id>"
  KEYCLOAK_CLIENT_SECRET: "<path:clearing-house/data/idp#client-secret>"
